### PR TITLE
Add browser notifications

### PR DESCRIPTION
**Pull request by mluhta**
Adds browser notifications for new open alerts as requested in #299

### CODE REVIEW

**Comment by satterly** [comment]
Thanks for the PR however the original enhancement request suggests that it should be possible to filter by environment or some other attribute. I'm concerned that without that option this show notification feature will overwhelm users. 

Also it seems it only displays the words 'New Alert". Wouldn't it be more useful to include text from the actual alert in the title and body?

Lastly you haven't included translations for German or French.

**Comment by mluhta** [comment]
The main improvement here is that this lets the users configure the OS/browser notification sound as they like.

I agree that the notification would be better if it had the alert title & description, I can take a look on how to implement them. I guess if we would keep track of every alert where notification has already been sent we can send the notification once per new open alert. That would bring the amount of notifications down too.

I don't know any German or French so I can't help with translating those.

**Comment by satterly** [comment]
> The main improvement here is that this lets the users configure the OS/browser notification sound as they like.

If that's the case, then that information should have been in the original description. Also adding a screenshot or even better, an animated gif, can really help the reviewer in understanding the benefit of a change.

There is no need to keep track of every alert. That's what `isNewOpenAlerts` does here...
```
          if (this.isNewOpenAlerts) {
            this.playSound()
            this.showNotification()
          }
``` 

And google has this website where you type in the word in english and it gives you the word in any other language in the world. Try it ;) https://translate.google.com/

**Comment by satterly** [comment]
This doesn't work. I tried running the branch and all I got was this error ...

Screenshot 2020-05-28 at 18 50 33

... even though notifications were enabled...

Screenshot 2020-05-28 at 19 08 12

**Comment by mluhta** [comment]
It's probably because notifications are only supported when using HTTPS https://developer.mozilla.org/en-US/docs/Web/API/notification. They worked for me with HTTP but localhost is probably an exception. It needs a check for this or some message for the user though.

> There is no need to keep track of every alert. That's what `isNewOpenAlerts` does here...

`isNewOpenAlerts` only tells me if there are open alerts, right? If I want to show a notification only once per alert (so not on every refresh) I have to keep track of already shown notifications. I have a demo of this already working on my end, and it looks like it's the best way to add notifications in. I'll try to finish it and update the pull request on weekend.

image

`isNewOpenAlerts` filters on the chosen environment already so I was thinking of using the same filter for notifications too.

**Comment by satterly** [comment]
Ok it works on localhost. My initial impression is that it's incredibly annoying. It is very distracting as it just continually pops in and out, every few seconds. So currently I don't see browser notifications adding any value at all. 👎

**Comment by satterly** [comment]
Closing due to inactivity. If you believe this issue has been closed prematurely please provide more information to help progress the issue. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Pull request closed without merging**
