### PR TITLE
Add internationalization (fr, en)

### PR DESCRIPTION
**Pull request by randreetti**
- use of plugin vue-i18n to allow translation of most of the menus
- a specific directory locales has been added to store all translations depending on the language
- So far only french has been added but supplemental translations should be easy
- We added a new setting storing the language preference for each user in the current user table
- a new select component is available in the webui to choose the language preference

### CODE REVIEW

**Comment by JoveYu** [comment]
any update? i can help for zh-CN

**Comment by satterly** [comment]
Thanks for this. It looks really good. However I won't be able to merge until the tests pass - can you have a go at fixing the failing test? Thanks.

@JoveYu once this is merged I'd happily take a PR for Chinese. Thanks.

**Comment by randreetti** [comment]
> any update? i can help for zh-CN

Yes, you can help me for zh-CN @JoveYu . You need the langage file ?

**Comment by randreetti** [comment]
> Thanks for this. It looks really good. However I won't be able to merge until the tests pass - can you have a go at fixing the failing test? Thanks.
> 
> @JoveYu once this is merged I'd happily take a PR for Chinese. Thanks.

@satterly , i try to fix that but i am not good in development and i don't know how to fix the require.context problem. I am on it, if you want to help me, you are welcome :).

**Comment by satterly** [comment]
> > @JoveYu once this is merged I'd happily take a PR for Chinese. Thanks.

@JoveYu Translation for Chinese gladly accepted if/when you have the time.

**Comment by webringer** [comment]
Hi Nick
I am bilingual native speaker in both Russian/Ukrainian I've added Russian translation attached.
[ru.js.zip](https://github.com/user-attachments/files/17844013/ru.js.zip)

**Pull request merged**
