### PR TITLE
Redirect to end session URL if returned by API on logout

### PR DESCRIPTION
**Pull request by satterly**
See alerta/alerta#1122

### CODE REVIEW

**Comment by levkar** [comment]
very nice PR but breaks npm install (thus docker build etc.). Here's the npm log:

17 http fetch GET 401 https://npm.pkg.github.com/@alerta%2fvue-authenticate 753ms
18 silly fetchPackageMetaData error for @alerta/vue-authenticate@^1.4.2 Unable to authenticate, need: Basic realm="GitHub Package Registry"

Maybe it's better to send the fix to original vue-authenticate repo?

**Comment by satterly** [comment]
I would prefer to use the upstream version of vue-authenticate however that repo hasn't seen any activity for 9 months. I'll fix the docker build and submit the patch upstream and see what happens.

**Comment by levkar** [comment]
Thanks for the fast response. They might accept, who knows.

**Comment by satterly** [comment]
@levkar I've created a PR here https://github.com/dgrubelic/vue-authenticate/pull/193 Maybe it might help if you upvote it.

**Pull request merged**
