### PR TITLE
List all notes and show status note if any

### PR DESCRIPTION
**Pull request by satterly**
Screenshot 2019-08-18 at 08 54 59

### CODE REVIEW

**Comment by satterly** [comment]
@strangeman @vykulakov Please review.

**Comment by satterly** [comment]
I'll merge this for now and iterate on it later if required.

**Comment by vykulakov** [comment]
Thank you for this improvement - it is really helpful and convenient now.

But I see two problems with the current approach:
1. I cannot edit/remove an old note. As a result, I must always see all notes which I left. Even those which are not actual now. In some cases, it may be helpful to see all alert notes, but in other cases, it will be confusing to see old unactual notes. It happens because you try to use alert history to store notes. But in my vision, they should be different and independent entities. So alert history should contain only changes in alert notes/state/status/severity and so on. And alert notes should contain all alert notes with a possibility to add/edit/remove them.
2. We won't see notes if there are more than 100 history records. It is very unexpected to suddenly lose all notes for an alert. It may happen for flapping alerts, for instance, or for alerts with a long history (which live years). The reason for this behaviour is also using alert history to store notes.

Nonetheless, status comments work fine and I don't see any obvious problems with them right now. We may lose the user's comment when alert severity is changing, though, but I'm not sure about it and should 
test this behaviour.

**Comment by vykulakov** [comment]
What I see (pay attention to comment content):
image

**Comment by satterly** [comment]
Thanks for the feedback. You have raised valid concerns. I'll keep track of this issue and will consider the improvements you have suggested in the near future. In the meantime, further comments and feedback are always welcome.

**Comment by satterly** [comment]
Discussion moved to #235

**Pull request merged**
